baseURL = 'https://colpalm.github.io/personal-site/'
languageCode = 'en-us'
title = 'ColPalm'
theme = 'cp-theme'


[params]
 # Site logo path (relative to the static folder)
 logo = "images/pineapple.png"

[[menus.main]]
name = 'ABOUT'
pageRef = '/about'
weight = 10

[[menus.main]]
name = "PROJECTS"
pageREf = '/projects'
weight = 20

[[menus.main]]
name = 'POSTS'
pageRef = '/posts'
weight = 30

[[menus.main]]
name = 'TAGS'
pageRef = '/tags'
weight = 40

[caches]
 [caches.images]
  dir = ':cacheDir/images'